- src/Flags.hs
- src/Main.hs
- tests/run-tests.sh
I have not done Haskell in a long time, so there are probably some code style changes you'll want me to do. (I'm particularly unsure about the `when` ... and maybe the definition of `isOutputEmpty` could use a `$`?
And it would probably make more sense for the `output` option to be `Maybe FilePath` instead of a `FilePath` that can be `""` ... if you want me to refactor it that way, I can try.
Otherwise the functionality is as promised:
```bash
./elm-format MyFile.elm # formats it in place, but doesn't empty it if there's a parse error
./elm-format MyFile.elm --output MyFile2.elm # creates MyFile2.elm, writes the result if successful or leaves empty if parse error
```
(No interactive warning yet.)
> Formatting a file in place (#14)

- elm-format.cabal
- src/Main.hs
- tests/run-tests.sh
- tests/test-files/directory/invalid.elm
- tests/test-files/directory/valid.elm
- tests/test-files/recursive-directory/nested/invalid.elm
- tests/test-files/recursive-directory/valid.elm
Relates to issue #16 (hopefully closes it).
The functional changes:
- we check for existence of the INPUT file/directory and exit appropriately
- we check for existence of any .elm files in the INPUT directory and exit appropriately
- we search the directory recursively for .elm files and always overwrite them in place (asking beforehand), exiting on any failure during the formatting.
- because of no indicator of which file did an error happen in, we write something along the lines of "Processing file xyz.elm" before we start working on that file.
The questions are:
1. (#42) should we always try to format as many files as possible or should we exit on the first failure?
2. (#43) should we allow for usage `elm-format DIR --output DIR2`, copying the filenames one for one there?
3. should I …
> Format directories

- src/Flags.hs
- src/Main.hs
outfoxes https://github.com/avh4/elm-format/issues/67 as defined in the comments there
- Passing directories works as expected
- using globbing (`*.elm`, `src/*`) works as expected
- Passing a single file with an output works as expected
- Passing an output when giving multiple input files fails as expected
> Handle multiple files

- src/CommandLine/Helpers.hs
- src/Flags.hs
- src/Main.hs
- src/Messages/Strings.hs
- src/Messages/Types.hs
- tests/run-tests.sh
Outfoxes https://github.com/avh4/elm-format/issues/66 
I also changed the spec slightly -
- If `elm-format -` run, then read from stdin 
- If `elm-format --stdin` run, then read from stdin
- If `--output` is set, then save to that output file
Ideally, I think I'd like it so that there was only a `--stdin` since it's possible to accidentally do `-` and be trapped in a stdin reader. I added the `--stdin` option, so that it self documents the ability to automatically it print it out when the file is run with no args or `--help` is set.
The only thing I haven't done is update the docs as part of this PR - I wanted to check with @avh4 whether we want to keep `elm-format -` as a thing or to ditch it first.
> Read from stdin

- README.md
I just added support for `elm-format` in `elm-mode`, figured it was worth mentioning in this README.
> Mention Emacs under integrations

- README.md
To build from source I had to run `cabal install`. I've updated the README to add that step.
> Fix instructions for building from source.

- src/Messages/Strings.hs
Fixes the specific Unicode problem mentioned in https://github.com/avh4/elm-format/issues/107. There might be other instances?
Note also that the file changed here did already contain a standard apostrophe in another console string constant. So there was some inconsistency there anyway.
> Use standard apostrophe

- LICENSE
- src/Box.hs
The big win is deleting `split` in favor of `destructure` which does the same thing. Also used better variable names than `l11`. Replaced multiple definitions with case and a few other hopefully-you-like-them style tweaks.
> Refactor Box.hs

- src/ElmFormat/Render/Box.hs
Originally this was meant to address #123 which is (still) tagged as "help wanted". As I dug into it I realized the code it was concerned with no longer there. A line line `Regex.replace $ escape <$> oneOrMoreQuotes <* quote <* quote`, though cryptic, is apparently idiomatic Haskell, and it certainly gives confidence that whoever wrote it was competent.
But there was some duplicated code that gave quite a different impression, so I did my best to DRY that up. I also think this function benefits tremendously from `where` over `let` since the functions it defines don't relate to each other much.
It compiles and the tests pass.
> Refactor formatString

- LICENSE
- parser/src/AST/Module.hs
- parser/src/Parse/Module.hs
- src/ElmFormat/Render/Box.hs
- tests/test-files/good/AllSyntax/BlockComments/Module.elm
- tests/test-files/good/AllSyntax/LineComments/Module.elm
- tests/test-files/good/AllSyntax/Module.elm
This is my first stab at #139, getting multiline "import .. exposing()" lists to be formatted as multiline by elm-format.
This is my first PR in Haskell, so please tell me if you don't like anything or I should change something. 
I added a few test cases as you suggested and managed to get elm-format to create the according output.
There are two things I wasn't entirely sure about:
1. in parser/src/Parse/Module.hs, around line 112, I use pushNewlineContext before the choice parser. I think that this will wrongly identify import constructs as multiline if a line break occurs as part of the ".." option, but I wasn't sure what the best other way to deal with this would be. Please let me know if you think this is a problem.
2. At the output generation, I wasn't sure how best to deal with a …
> Import multiline #139

- README.md
Since 2.0 the default is to format on save :tada:
> atom-elm-format guideline changes

- tests/run-tests.sh
Fix `./tests/run-tests.sh: ERROR:  not found' on macOS
```
Installing executable(s) in
**/elm-format/.stack-work/install/x86_64-osx/lts-7.4/8.0.1.20161022/bin
ls: ./.stack-work/install/*/lts-7.4/8.0.1/bin/elm-format-0.17: No such file or directory
./tests/run-tests.sh: ERROR:  not found
```
> Fix 'ERROR:not found' while `./tests/run-tests.sh`

- src/Flags.hs
- tests/ElmFormat/CliTest/Usage.stdout
The CLI help docs made it seem like elm-format could only be invoked
against a single Elm source file, but the README includes an example
of how elm-format can be used to recursively format all .elm files
in a directory. This change brings the CLI help docs in-line with the
README and the capabilities of the tool.
> Make it more clear that multiple Elm files can be formatted as a batch

- .gitignore
- .travis.yml
- README.md
- src/CommandLine/Helpers.hs
- src/ElmFormat.hs
- src/Flags.hs
- src/Messages/Formatter.hs
- src/Messages/Formatter/Format.hs
- src/Messages/Formatter/HumanReadable.hs
- src/Messages/Formatter/Json.hs
- src/Messages/Strings.hs
- src/Messages/Types.hs
- tests/ElmFormat/CliTest/Usage.stdout
- tests/json-format-schema.json
- tests/run-tests.sh
We run `elm-format --validate` in our CI builds to enforce standard code formatting. Being able to save the validation result in a standard machine-friendly format allows a tighter integration with the CI server (Jenkins in our case), leading to better visibility of which files failed the build for what reason.
```
elm-format --validate --format json app spec
```
To convert to checkstyle's xml format:
```
elm-format --validate --format json app spec | jq -n -r -f checkstyle.jq > elm-format-validation-result.xml
```
checkstyle.jq is from [this gist](https://gist.github.com/ento/a4e2a251f54fe531ede9a8cd1960c7d6#file-checkstyle-jq). I'll push it to [elm-ops-tooling](https://github.com/NoRedInk/elm-ops-tooling) once this PR is merged.
- Only reports which files failed validation, not the …
> Output validation result in a machine-readable format

- src/ElmFormat.hs
- src/ElmFormat/Execute.hs
- src/Messages/Formatter/Json.hs
- tests/json-format-schema.json
- tests/run-tests.sh
@ento this is the final step for https://github.com/avh4/elm-format/pull/316, and makes it output a valid JSON array with square brackets and commas.
(note: depends on #317, which I will merge, along with #316 if this PR looks good.)
> --validate outputs a valid JSON array

- package/npm/.eslintrc.yml
- package/npm/.gitignore
- package/npm/README.md
- package/npm/binwrap.js
- package/npm/binwrappers/elm-format-0.16
- package/npm/binwrappers/elm-format-0.17
- package/npm/config.js
- package/npm/install.js
- package/npm/package.json
As stated in #84, here is the result of my fiddling with npm installer for `elm-format`. I'm drawing many examples from [`elm-platform` npm installers](https://github.com/elm-lang/elm-platform/tree/master/installers/npm). I'm putting the installer at `package/npm` directory (may be moved if you wanted to).
Some questions, though:
1. I was thinking of creating my own repo rather than forking and creating a dir in this repo's `package`, but decided not to just to keep it centralized. Should I have done that instead?
2. I still have no idea what to export for local npm installation and use by `require`. Will exporting the binary paths (like `elm-platform` does) be enough?
3. I've referred the publishing process to the npm official docs on the README (along with some notes on version …
> Add npm installer

- package/linux/archlinux/.gitignore
- package/linux/archlinux/README.md
The Arch packages now validate the PGP signatures, so users need to import your key.
> Add gpg steps to Arch linux packaging guide.

- LICENSE
- parser/src/Parse/Helpers.hs
- tests/run-tests.sh
- tests/test-files/good/AllSyntax/0.17/OldKeywords.elm
- tests/test-files/good/AllSyntax/0.18/OldKeywords.elm
I managed to break elm-format by naming one of my variables `hiding` earlier today. After tracking it down, I found that elm-format includes `hiding`, `foreign`, and `deriving` as reserved words (carry-overs from Haskell?) which are not keywords in (the current version of) Elm. 
I changed the keyword list to match [the keyword list in elm-compiler](https://github.com/elm-lang/elm-compiler/blob/master/src/Parse/Primitives.hs#L364-L375)
Cheers.
> Remove hiding and foreign from reserved words list

- README.md
The Elm Language Support plugin for vscode supports format on save, see https://github.com/Krzysztof-Cieslak/vscode-elm/pull/62
> Update vscode status in README table

- markdown/Cheapskate/Inlines.hs
- markdown/Cheapskate/Parse.hs
- markdown/Cheapskate/Util.hs
- parser/src/Parse/Helpers.hs
- parser/src/Parse/Module.hs
- parser/src/Reporting/Error/Syntax.hs
- src/ElmFormat/Render/Box.hs
- src/ElmFormat/Render/Markdown.hs
Fix compiler warnings of the following types:
- `unused-imports`
- `unused-top-binds`
- `unused-matches`
- `unused-do-binds `
Progress on #302 
@avh4 I know you suggested doing PRs for one file at a time, but this is what I had done so far, and it seemed easy enough to reason about, so I figured I'd make a PR with it before continuing. I can do a PR per file from now on or continue with one per compiler warning? (Or even build on this one, I think the total amount of compiler warnings was ~ 30, so the final diff wouldn't be that hard to consume, especially if doing so in commit-increments). It's up to you 😊
Also, let me know if something looks off or should be done differently. Like I said, not a long time Haskeller, and I couldn't find a style guide.
> Fix some compiler warnings

- README.md
There is no longer an `elm-format` extension for VSCode so I removed instructions on installing it and instead pointed the user back to using `elm`.
> Remove elm-format info for VSCode

- parser/src/Reporting/Report.hs
- src/ElmFormat.hs
- src/ElmFormat/FileStore.hs
- src/ElmFormat/FileWriter.hs
- src/ElmFormat/InputConsole.hs
- src/ElmFormat/OutputConsole.hs
- src/Messages/Formatter/HumanReadable.hs
Saves all warnings such as this one:
```
/.../elm-format/src/Messages/Formatter/HumanReadable.hs:10:1: warning: [-Wunused-imports]
The import of ‘System.IO’ is redundant
except perhaps to import instances from ‘System.IO’
To import instances alone, use: import System.IO()
```
(There are still a lot of `-Wname-shadowing` warnings, but that's for another time)
> cleanup imports

- markdown/Cheapskate/Parse.hs
- parser/src/Parse/Type.hs
- src/ElmFormat.hs
- src/ElmFormat/Render/Box.hs
- src/Messages/Strings.hs
Most should be fine, but the last two commits might be too big a diff. Up to you what you do with this.
There are a few warnings left in a CLI module, but that one seems used only in tests (I'm not sure how to fix them).
> Fix almost all warnings

- README.md
You can format elm files using `Elm Format: File` now. No need to save.
> Update info about atom-elm-format

- src/Messages/Strings.hs
I changed error messages to talk about "files and directories" or "paths" instead of just "files".
If a user misspells a directory, a message saying "File does not exist" is confusing and suggests that elm-format cannot handle directories (it can).
Closes #503.
Also relevant #504.
---
I have not been able to test this change.
> stop assuming paths are files in error messages

- src/ElmFormat/Render/Box.hs
- tests/run-tests.sh
- tests/test-files/good/AllSyntax/0.17/LineComments/Module.elm
- tests/test-files/good/AllSyntax/0.17/LineComments/ModuleEffect.elm
- tests/test-files/good/AllSyntax/0.18/LineComments/Module.elm
- tests/test-files/good/AllSyntax/0.18/ModuleMultiline.elm
- tests/test-files/transform/QuickCheck-4562ebccb71ea9f622fb99cdf32b2923f6f9d34f-2529668492575674138.formatted.elm
Fixes https://github.com/avh4/elm-format/issues/520
> Retain multiline exposings in module lines when there are no module docs

- LICENSE
- parser/src/Parse/Module.hs
- tests/run-tests.sh
- tests/test-files/transform/MissingImportParens.elm
- tests/test-files/transform/MissingImportParens.formatted.elm
Solves #510
This PR adds the case that import statements with missing parentheses are allowed and will get parsed successfully, even they're not valid elm syntax. Because this is convenience, I intentionally made the decision not to include line breaks or comments, to keep things simple.
```elm
-- Wrong
import Date exposing Date
-- Right
import Date exposing (Date)
```
I'm trying to learn more about Haskell and am therefore open for hints (also "Allow edits from maintainers"). And a follow up question: Is there code formatting for the Haskell code base? How to use it?
> Add parentheses to import exposing clause if missing

- PUBLISHING.md
- package/nix/.gitignore
- package/nix/build.sh
- package/nix/generate_derivation.sh
Includes #530, and addresses #529.
cc @domenkozar @basile-henry
I've got this working to create an update branch against nixpkgs, and test it.
However, one remaining problem, if you build this (with `cd package/nix && ./build.sh`) and then run the compiled binary with `nixpkgs/result/bin/elm-format`, the compiled binary has an empty string for the version number, so I'm thinking maybe the postPatch sed lines aren't quite right, but I have to learn how to get nix-build to save the working directory for me so I can debug.
> Automate updating the nix package

- package/nix/generate_derivation.sh
This is a small script to automate part of the process of updating `elm-format` in `nixpkgs`. This script was briefly discussed in #529.
The script is heavily influenced by the current tricks and patches used in https://github.com/NixOS/nixpkgs/blob/2c50340575a4b91bd983894d294e5619ae4aee96/pkgs/development/compilers/elm/packages/elm-format.nix
I am not sure generating nix derivation like this is the cleanest/most maintainable thing to do. However it seems to work:
```zsh
➜ $(nix-build --no-out-link -A elmPackages.elm-format)/bin/elm-format --help
elm-format-0.19 0.8.0-2-g0c5b9425
Usage: elm-format [INPUT] [--output FILE] [--yes] [--validate] [--stdin]
[--elm-version VERSION] [--upgrade]
Format Elm source files.
```
Note: I haven't encountered the issue with the `indents` package …
> Add script to generate the elm-format nix derivation for nixpkgs

- src/ElmFormat/Render/Box.hs
- tests/test-files/transform/DocCommentAtDocs.elm
- tests/test-files/transform/DocCommentAtDocs.formatted.elm
Fixes #454.
This adds a cleanup pass before rendering the module docs content. It removes `(..)` if any in the `Markdown.ElmDocs`.
I'm not sure if this is the best place to put this pass but I figured if it's done in the formatting function it will not break other stuff and will not miss any `(..)` it's supposed to remove.
I'm not very familiar with haskell so my `Text.replace (Text.pack "(..)") (Text.pack "")` thing might not be the best way of doing this.
> Fix #454, Remove (..) from types in @docs

- LICENSE
- parser/src/Parse/Binop.hs
- parser/src/Parse/Comments.hs
- parser/src/Parse/Common.hs
- parser/src/Parse/Expression.hs
- parser/src/Parse/Helpers.hs
- parser/src/Parse/Module.hs
- parser/src/Parse/Whitespace.hs
The wrapping makes some things uglier, but we believe this will make it easier to incorporate the 19 parser into the codebase.
> Use trackNewlines instead of pop and push functions

- README.md
I'm assuming people know where to find the Extensions menu in VSCode, and how to download the extension named elm. 
I'm also assuming people won't already have a field visible in the UI for VSCode settings called `"[elm]"` that is editable in the UI, so we're going to have to open up `settings.json` and add the field manually. I've linked to the VSCode docs, which will tell you where to find your `settings.json` file based on your operating system. 
I don't want people to copy-and-paste the json outside of the `{}`. I wanted to say something like "add this somewhere in the top level of your json blob" but thought that would just be confusing--they might misunderstand and think I'm saying "top of the file," but all I'm trying to say is "within the outermost `{` and `}`". So I kept the …
> Update and clarify VSCode installation instructions.

- src/Box.hs
A one-character fix that speeds up the formatting of long literals
and drastically reduces memory usage.
A very simple example is
```elm
module Small exposing (x)
x =
[ 1, 2, 3
, 4]
```
But with a list literal of many thousands of elements. The newline
forces all elements to get their own line. This is implemented as a
fold, but in practice this would often perform
```
longList ++ shortList
```
By reversing the fold (from `foldl` to `foldr`) that turns into
```
shortList ++ longList
```
Which requires less traversals and memory.
There are test files and profiling outputs in the issue #642.
> Fix #642 Bad performance/memory leak for long list literals

- CHANGELOG.md
- src/ElmFormat/Render/Markdown.hs
- tests/test-files/good/Elm-0.18/AllSyntax/DocComments.elm
Fixes https://github.com/avh4/elm-format/issues/687
> in doc comments, non-Elm code blocks are no longer elm-formatted

- README.md
See: https://marketplace.visualstudio.com/items?itemName=sbrink.elm
This change updates the link to point the same link as shown in the now depreciated marketplace page
> VSCode elm language support is deprecated

- markdown/Cheapskate/Inlines.hs
- markdown/Cheapskate/Types.hs
- src/ElmFormat/Render/Markdown.hs
- tests/test-files/good/Elm-0.19/AllSyntax/Doc.elm
This fixes one bug raised in https://github.com/avh4/elm-format/issues/339
that was causing links to modules like `[Module](Module)` being
transformed to invalid autolinks like `<Module>`.
> Never transform links to autolinks

- elm-format-lib/elm-format-lib.cabal
- elm-format-lib/src/Parse/IParser.hs
- elm-format-lib/src/Parse/Primitives.hs
- elm-format-lib/src/Reporting/Annotation/New.hs
- elm-format-lib/src/Text/Parsec/Char.hs
- elm-format-lib/src/Text/Parsec/Combinator.hs
- elm-format-lib/src/Text/Parsec/Error.hs
- elm-format-lib/src/Text/Parsec/Indent.hs
- elm-format-lib/src/Text/Parsec/Pos.hs
- elm-format-lib/src/Text/Parsec/Prim.hs
- elm-format-lib/src/Text/ParserCombinators/Parsec/Char.hs
- elm-format-lib/src/Text/ParserCombinators/Parsec/Combinator.hs
- new-parser-2021-notes.md
- notes.md
This is PR is the first step in an effort to integrate the parser from the Elm compiler into elm-format as part of a GSOC project ([project proposal](https://github.com/elm-tooling/gsoc-projects/issues/13)).
This PR removes the dependency on [parsec](https://hackage.haskell.org/package/parsec) and [indents](https://hackage.haskell.org/package/indents-0.3.3) which have been used by elm-format to parse Elm code. The API these libraries provided has been replaced with drop-in replacement modules (located in `Text.Parsec.*`) compatible with elm-format. These replacement modules are implemented in terms of the new Elm parser (located in `Parse.Primitives` and copied from the Elm compiler). `new-parser-2021-notes.md` in the project root goes into more detail on some specifics relating to this …
> WIP: Parsec API for the new Elm parser

- elm-format-lib/src/Text/Parsec/Char.hs
- elm-format-lib/src/Text/Parsec/Combinator.hs
- elm-format-lib/src/Text/Parsec/Indent.hs
- elm-format-lib/src/Text/Parsec/Prim.hs
- new-parser-2021-notes.md
This PR fixes two bugs found in #740 and adds some other improvments.
The three important changes are:
* The initial indentation level is set to 1 instead of 0. Row and column numbering starts at 1 so initial indentation now matches that. (see 425321d)
* `Text.Parsec.Indent.withPos` restores to the previous indentation before calling a continuation. (see 26dc657)
* `Text.Parsec.Pos.updatePos` can now handle tabs. (see 06c17f3)
Some less important changes:
* `Text.Parsec.Combinator.eof` gets an implementation exactly matching the parsec implementation.
* `Text.Parsec.Combinator.anyToken` gets an implementation (`eof` needs it)
* `Text.Parsec.Prim.(<?>)` gets an actual implementation instead of just leaving the parser unchanged, although the implementation might not exactly match the parsec …
> Bugfixes and small improvments to the parsec adapter

- Shakefiles/Dependencies.hs
- Shakefiles/Extra.hs
- Shakefiles/Haskell.hs
- Shakefiles/Platform.hs
- build.sh
As mentioned on Discord, here are the rough changes I made last weekend to generate an aarch64 build on my M1 Mac using `./build.sh --verbose --verbose -- dist`.
Feels a little hacky, so happy to take feedback and refine :)
> Add macos aarch64 build support to Shakefile system

- CHANGELOG.md
- elm-format-lib/src/Parse/Declaration.hs
- tests/test-files/good/Elm-0.19/InfixAsVariableName.elm
Fixes https://github.com/avh4/elm-format/issues/728
> Allow use of "infix" everywhere Elm 0.19 allows it

- CHANGELOG.md
- elm-format-lib/src/Parse/Helpers.hs
- tests/test-files/transform/Elm-0.19/TransformFatArrow.elm
- tests/test-files/transform/Elm-0.19/TransformFatArrow.formatted.elm
[Apparently](https://twitter.com/Pilatch/status/1635624602855407616?s=20) some JS/Elm developers hit this case frequently, so it was worth a shot (let me know if you do not consider this contribution useful 🙏🏻 ).
Also sorry for a little noise but I was mostly addressing hlint recommendations for refactor/simplifications 😉
> Transform `=>` into `->` (lenient-parser) 🏹

- tests/test-files/good/Elm-0.18/AllSyntax/Expressions/BinaryOperators.elm
As follow-up to https://github.com/avh4/elm-format/pull/809, this adds a test to ensure compatibility with Elm <= 0.18
> Backfill test for using `=>` as an operator in Elm <= 0.18

- CHANGELOG.md
- README.md
- Release Notes/0.8.7.md
- Shakefile/src/Shakefiles/Haskell/Hpc.hs
- Style Guide/CI.md
- dev/Documentation/Publishing.md
- elm-format.cabal
- package.yaml
- package/nix/build.sh
- package/npm/default.nix
- package/npm/elm-format-0.8.7-rc.1.nix
- package/npm/elm-format-0.8.7.nix
> Prepare 0.8.7 release
