src/CommandLine/Helpers.hs, src/Flags.hs, src/Main.hs, tests/run-tests.sh
=> Overwrite prompt (#15)

src/Flags.hs, src/Main.hs, src/Messages/Strings.hs, src/Messages/Types.hs
Fixes #45.
Is it appropriate to do the same thing to Flags.hs? If yes, which parts?
=> Replace hardcoded strings with typed messages

src/Box.hs, src/ElmFormat/Render/Text.hs, tests/BoxTest.hs
=> Use Data.Text instead of String

README.md
Updated the README docs with more examples of usage and a header explaining what each one is expected to do
=> improve readme docs on usage

README.md
Merge if & when Homebrew/homebrew#48624 is merged.
=> update readme to include Homebrew installation

README.md
elm-format automatically on save is now default.
=> Update Sublime Text instructions.

src/Flags.hs, src/Main.hs, src/Messages/Strings.hs, src/Messages/Types.hs, tests/run-tests.sh
As discussed on slack:
- Runs elm format
- Does not modify files
- Prints the names of the files that would change
This will cover what we need for OPs tooling for running efm on our CI!
=> Add the ability to run dry runs

README.md
in context: "It makes code **easier to maintain**, because you can no longer have diffs related only to formatting; every diff necessarily involves a material change"
=> change 'necessary' to 'necessarily'

README.md
Hi!
Many thanks for elm-format!
Please consider this little update of the Emacs section.
Best regards,
=> Update install section for Emacs

README.md
This should take care of #176.
=> Update README to mention VSCode

src/ElmFormat.hs, src/Messages/Strings.hs, src/Messages/Types.hs
=> fix #186: make console output less verbose

README.md
Sublime does format-on-save by default: https://github.com/elm-community/Elm.tmLanguage/blob/master/Settings/Elm%20Language%20Support.sublime-settings#L5
=> Update Sublime's format-on-save status

package/linux/archlinux/.gitignore, package/linux/archlinux/README.md, package/linux/archlinux/Vagrantfile
=> Instructions for updating Arch packages.

README.md
=> Revert "atom-elm-format guideline changes"

README.md
Enhancement to LightTable installation instructions to make it more explicit for new users.
=> Enhancement to LightTable installation instructions.

parser/src/Parse/Helpers.hs, tests/run-tests.sh, tests/test-files/good/Export.elm
=> removed "export" from reserved

README.md
Took a guess at the missing word in the readme file.
=> Add missing word in readme

README.md
=> Add link to official Elm style guide

tests/test-files/good/AllSyntax/0.19/Expressions.elm
=> Add test for Module.record.field

src/ElmFormat/Render/Box.hs, src/ElmFormat/Upgrade_0_19.hs, tests/run-tests.sh, tests/test-files/transform/Elm-0.19/ConvertBasicsModBy.elm, tests/test-files/transform/Elm-0.19/ConvertBasicsModBy.formatted.elm
Fixes https://github.com/avh4/elm-format/issues/477
=> 0.19 upgrade: convert % to modBy

src/ElmFormat/Render/Box.hs, tests/test-files/good/AllSyntax/0.19/Literals.elm
=> 0.19: Remove unnecessary workaround for non-breaking space

tests/run-tests.sh
and address SC2230, which is newly added
=> Update to shellcheck 0.5.0

src/ElmFormat/Filesystem.hs
=> Use System.FilePath functions to check filenames and extensions

README.md
Should be fixed according to https://github.com/Krzysztof-Cieslak/vscode-elm/commit/392e9637c7ec5765f644a5269ab2d582e55eb17c
=> Update vscode table in readme

CHANGELOG.md, src/ElmFormat/Render/Box.hs, tests/test-files/good/AllSyntax/0.18/DocComments.elm
=> WIP for 0.8.1

LICENSE
As requested in https://github.com/avh4/elm-format/pull/565#issuecomment-427716002.
=> Added myself in the LICENSE file

parser/src/AST/Json.hs, tests/test-files/good/AllSyntax/0.18/Expressions.json, tests/test-files/good/AllSyntax/0.18/Literals.elm, tests/test-files/good/AllSyntax/0.18/Literals.json, tests/test-files/good/AllSyntax/0.19/Literals.elm, tests/test-files/good/json/ExternalReferences.json
just expanding on the work we did a while back. Added floats, chars, strings, and expanded the rest of the values for TODOs.
=> add a few more cases in the JSON output

parser/src/AST/Declaration.hs, parser/src/AST/Json.hs, parser/src/AST/Pattern.hs, parser/src/AST/V0_16.hs, parser/src/Parse/Comments.hs, parser/src/Parse/Helpers.hs, parser/src/Parse/Type.hs, parser/src/Reporting/Annotation.hs, src/AST/MapExpr.hs, src/AST/MapNamespace.hs, src/ElmFormat/Render/Box.hs, src/ElmFormat/Upgrade_0_19.hs, tests/test-files/good/Elm-0.18/AllSyntax/Expressions.json, tests/test-files/good/Elm-0.18/AllSyntax/Literals.json, tests/test-files/good/Elm-0.18/AllSyntax/Module.json, tests/test-files/good/json/ExternalReferences.json
@BrianHicks FYI, this rebases the https://github.com/BrianHicks/elm-format/tree/json branch we started, so you can delete that on your repo.
=> JSON type annotations

.github/workflows/Build Windows release.yml, CHANGELOG.md, PUBLISHING.md, README.md, Release Notes/0.8.3.md, Style Guide/CI.md, elm-format.cabal, package/collect_files.sh, package/npm/package.json, package/sign_files.sh
- 7610678611b326a0d2f54949a865ab85e6d5c253  elm-format-0.8.3-linux-x64.tgz
- 87913926b996add3d4c4afe313f422d78f0c6f58  elm-format-0.8.3-mac-x64.tgz
- e7c9d18879fbd03c592e56fa761de9262296a404  elm-format-0.8.3-win-i386.zip
- https://github.com/NixOS/nixpkgs/pull/81413
=> Prepare 0.8.3 release

.dockerignore, CHANGELOG.md, Dockerfile, Shakefile.hs, package/linux/build-in-docker.sh
This should make the linux binaries work both on alpine linux and on systems with glibc < 2.27
=> Build static linux binary

elm-format-lib/src/ElmFormat/AST/Shared.hs, elm-format-lib/src/ElmFormat/Render/Box.hs, package/nix/build.sh, tests/test-files/good/Elm-0.17/AllSyntax/LineComments/Module.elm, tests/test-files/good/Elm-0.17/AllSyntax/LineComments/ModuleEffect.elm, tests/test-files/good/Elm-0.18/AllSyntax/LineComments/Module.elm, tests/test-files/transform/Elm-0.18/QuickCheck-4562ebccb71ea9f622fb99cdf32b2923f6f9d34f-2529668492575674138.formatted.elm
Rebased https://github.com/avh4/elm-format/pull/564
=> Fix formatting exports with commented lines

.github/workflows/CI.yml, README.md, Shakefile/build-elm-format.cabal, Shakefile/package.yaml, Shakefile/src/Main.hs, Shakefile/src/Shakefiles/Haskell.hs, dev/Documentation/Build Commands.md, dev/Documentation/README.md, dev/build.sh, shell.nix
Just some initial prep work for https://github.com/avh4/elm-format/issues/804
=> Build haddock docs for elm-format-lib

CHANGELOG.md, LICENSE, elm-format-lib/src/Parse/Expression.hs, tests/test-files/transform/Elm-0.19/ReplaceThenByOfInCase.elm, tests/test-files/transform/Elm-0.19/ReplaceThenByOfInCase.formatted.elm
=> Transform `case .. then` into `case .. of` (lenient-parser) 🛠

Shakefile/build-elm-format.cabal, Shakefile/package.yaml, avh4-lib/avh4-lib.cabal, avh4-lib/package.yaml, elm-format-lib/elm-format-lib.cabal, elm-format-lib/package.yaml, elm-format-lib/src/Data/Utf8.hs, elm-format-markdown/elm-format-markdown.cabal, elm-format-markdown/package.yaml, elm-format-test-lib/elm-format-test-lib.cabal, elm-format-test-lib/package.yaml, elm-format.cabal, package.yaml
Tidied up a package.yaml file by removing some unused dependencies.
=> Remove unused packages
